{{- if and (.Values.metrics.enabled) (eq .Values.metrics.type "prometheus") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "emqx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: prometheus
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      {{- if .Values.metrics.targetNamespaces }}
      {{- range .Values.metrics.targetNamespaces }}
      - {{ . }}
      {{- end }}
      {{- else }}
      - {{ .Release.Namespace }}
      {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: dashboard
      interval: {{ .Values.metrics.interval | default "15s" }}
      path: /api/v5/prometheus/stats
      {{- if .Values.metrics.basicAuth }}
      basicAuth:
        password:
          name: {{ .Values.metrics.basicAuth.secretName }}
          key: {{ .Values.metrics.basicAuth.passwordKey | default "password" }}
        username:
          name: {{ .Values.metrics.basicAuth.secretName }}
          key: {{ .Values.metrics.basicAuth.usernameKey | default "username" }}
      {{- end }}
      metricRelabelings:
        {{- if .Values.metrics.metricRelabelings }}
        {{- toYaml .Values.metrics.metricRelabelings | nindent 8 }}
        {{- end }}
  jobLabel: {{ .Release.Name }}-scraping
{{- end }}
